### PR TITLE
Adding unique visitor system.

### PR DESCRIPTION
**Pull request by Ryan-da-ghost**
Fixing issue #27 
Adding a session system 
Notes: 
- I don't know which file is shown to the users, so i added session_start to all files. 

Thank you for this great and amazing project!

### CODE REVIEW

**Comment by antonkomarev** [comment]
@Ryan-da-ghost but requests are coming from the GitHub proxy servers, they are stateless. How will it work?

**Comment by antonkomarev** [comment]
Here is a link for the reference: https://github.com/antonkomarev/github-profile-views-counter#why-does-the-counter-increase-every-time-the-page-is-reloaded

**Comment by Ryan-da-ghost** [comment]
> but requests are coming from the GitHub proxy servers, they are stateless. How will it work?

Hmm, every time the page gets loaded github makes a request to your website right ? 
On the request can't you set sessions to your own website and this will all work. 
Meaning : 
> You add the session system to https://komarev.com/ghpvc/ .
> When someone views the page https://komarev.com/ghpvc/ sets a session to its OWN domain name.
> The next time when it's called it will detect from https://komarev.com/ghpvc/ if a session has been set.
Also : 
Can't we somehow test this ? isn't there a demo url ?

**Comment by antonkomarev** [comment]
Only cheaters are going directly to the URL and counter is not increasing because we are increasing counter only from the GitHub service. You can open and refresh my counter: https://komarev.com/ghpvc/?username=antonkomarev

**Comment by antonkomarev** [comment]
Short answer - there is no way to determine if the same user refreshes your profile page on GitHub. GitHub protects users from this data leak.

**Comment by Ryan-da-ghost** [comment]
Intresting, another question : So you can't even add cookies in that case ?

**Comment by antonkomarev** [comment]
We can't do anything. We are receiving stateless server requests from one IP address with one user agent.

**Comment by antonkomarev** [comment]
```
[ User ] --request--> [ GitHub ] --request--> [ profile views counter ]
```

**Pull request closed without merging**
