### PR TITLE
Fix counter file race-condition vulnerability

### LINKED ISSUE #66: Race condition vulnerability causes counter reset
A user's counter can be reset by spamming requests, this happens due to a race condition while truncating and writing to a file. The following NodeJS script can be used to reset a user's counter:
```js
// Send requestsPerBulk requests in parallel (let's call that a bulk)
// Wait till they are done
// Repeat till a total of bulks * requestsPerBulk requests

// After each bulk, output the number of succeeded requests and the number of failed requests
(async () => {
  const url = process.argv[2];
  const bulks = parseInt(process.argv[3]);
  const requestsPerBulk = parseInt(process.argv[4]);
  const headers = new Headers();
  headers.append('User-Agent', 'github-camo');
  for (let i = 0; i < bulks; ++i) {
    const promises = [];
    console.time('bulk');
    for (let j = 0; j < requestsPerBulk; ++j) {
      promises.push(fetch(url, { headers }));
    }
    const results = await Promise.all(promises);
    const failed = results.filter((res) => res.status >= 400).length;
    console.log(`Bulk ${i}:- failed: ${failed}, succeeded: ${requestsPerBulk - failed}`);
    console.timeEnd('bulk');
    await new Promise((r) => setTimeout(r, 500));
  }
})();
```
Run it as
```bash
node script_name.js ghpvc_url 50 20
```
and observe the counter, it will reset at a certain point in time.

Here is an explanation of the race condition that happens according to my understanding:
Requests need to do the following:
- Read file, increment number
- Truncate file
- Put incremented number

The following race can happen between two requests (A and B):
- A: read file, increment number
- A: truncate file
- B: read file, increment number (oops read empty file, number is zero, incremented number is one!)
- A: put incremented number
- B: truncate file
- B: put incremented number (oops put one!)

This can be fixed by using a lock on the `views-count` file or by migrating to using a database management system that automatically handles concurrency issues.

### PR DESCRIPTION
**Pull request by Brikaa**
Fixes #66

### CODE REVIEW

**Comment by antonkomarev** [comment]
Thank you for the fix. I will try to look at it this weekend.

**Comment by antonkomarev** [comment]
Looks good, but I'm not sure we need to call `ftruncate($counterFile, 0);` because fwrite will overwrite all the file anyway.

**Comment by antonkomarev** [comment]
@Brikaa I've updated your solution:
- #68

**Comment by Brikaa** [comment]
@antonkomarev brilliant updates, thanks for pinging and explaining your code in the PR. Good call on avoiding errors from `getViewsCountByUsername`. This is actually where I suspected the problem was from in the first place. And good call on releasing the lock in the `finally` block.

**Comment by Brikaa** [comment]
I was thinking if we need a lock for appending content to the `views` files. But I found this in PHP's `fwrite` documentation:
```
Note:

If stream was [fopen()](https://www.php.net/manual/en/function.fopen.php)ed in append mode, fwrite()s are atomic (unless the size of data exceeds the filesystem's block size, on some platforms, and as long as the file is on a local filesystem). That is, there is no need to [flock()](https://www.php.net/manual/en/function.flock.php) a resource before calling fwrite(); all of the data will be written without interruption.
```

**Comment by antonkomarev** [comment]
We need a lock to avoid the second request to receive counter value before the first request is not finished.

**Comment by Brikaa** [comment]
@antonkomarev yeah, I was just wondering if we needed another lock on the `views` file.

The current implementation with one lock works because if the second request is another one trying to increment the counter, it will have to wait anyway since we read the counter after acquiring the lock.

I believe a problem that might happen is a deadlock if the system uses mandatory locking instead of advisory locking because we use `file_get_contents` after acquiring the lock and before releasing it. `file_get_contents` will be blocked.

**Comment by antonkomarev** [comment]
File is not locked for the `file_get_contents`.

**Comment by Brikaa** [comment]
If you mean the `file_get_contents` in the `incrementViewsCount` function, yes it does not respect the advisory lock. But it doesn't really matter since `file_get_contents` happens inside the "critical section". You can't reach this section unless you acquire a lock and you release the lock after this section.

Without mandatory locking instead of advisory locking I think that would cause a deadlock.

**Comment by antonkomarev** [comment]
Yes, we could release the lock earlier, but it looks like microseconds optimization.

**Comment by Brikaa** [comment]
@antonkomarev to understand what you mean, when do you think we should release the lock? In the `incrementViewsCount` function, we are doing:
- Acquire lock
- Read counter (`file_get_contents`)
- Increment counter
- Release lock

Both "Read counter" and "Increment counter" happen while the lock is acquired so there can't be race conditions despite the "Read counter" step using `file_get_contents` which doesn't respect the advisory lock.

**Comment by antonkomarev** [comment]
@Brikaa I'll try to draw a sequence diagram to visualize how 2 requests should work later this week. Do not have much free time now.

**Comment by antonkomarev** [comment]
@Brikaa 
ghpvc-file-couter-race drawio

**Comment by Brikaa** [comment]
Yes, that's how they currently work. Were you saying that we needed a further improvement in the code?

**Comment by Brikaa** [comment]
Or were you just explaining how the current locking works in that comment?

**Comment by antonkomarev** [comment]
@Brikaa I described why we need a lock. Right now it should work as I showed on the diagram. I don't see cases with a deadlock because of multiple simultaneous requests right now.

**Comment by Brikaa** [comment]
@antonkomarev ah yes, thanks. We don't disagree. I was not saying we do not need a lock for incrementing the counter, I was just saying we do not need one (and indeed we don't have one) for appending to the other `views` file because appending is atomic:

> I was thinking if we need a lock for appending content to the `views` files. But I found this in PHP's `fwrite` documentation:
> 
> > Note:
> > If stream was [fopen()](https://www.php.net/manual/en/function.fopen.php)ed in append mode, fwrite()s are atomic ?(unless the size of data exceeds the filesystem's block size, on some platforms, and as long as the file is on a local filesystem). That is, there is no need to [flock()](https://www.php.net/manual/en/function.flock.php) a resource before calling fwrite(); all of the data will be written without interruption.

About the deadlocks, I was just talking about a special case that might happen if we use a system in which `flock` does "mandatory locking" since that would cause `file_get_contents` to hang waiting for the lock to be released.

**Pull request merged**
