### PR TITLE
Feat: Abbreviation

### PR DESCRIPTION
**Pull request by Trkzi-Omar**

### CODE REVIEW

**Comment by Trkzi-Omar** [comment]
@antonkomarev, I think that this will do, but feel free to edit it as you see fits.

**Comment by antonkomarev** [comment]
You pushed changes to master, it's not great when you are contributing. Don't forget to create separate branches. I've made changes in your master branch, but after merging this PR you wouldn't be able to proceed make changes there, because your master would be conflicting with current master after squash.

**Comment by antonkomarev** [comment]
@Trkzi-Omar thanks for contribution! Your code is commited, but not pushed to production yet. I'll try to make it with next week, when some more critical changes will be completed.

**Comment by orhun** [comment]
This is a great feature, thanks for adding it @Trkzi-Omar!

@antonkomarev can you ping here once you deploy this please? I would like to add it to my profile.

**Comment by antonkomarev** [comment]
@orhun sure, I'll write about it here

**Comment by antonkomarev** [comment]
@orhun @Trkzi-Omar released. You can add `&abbreviated=true` to the URL

**Comment by orhun** [comment]
thanks, just added to my profile!

**Comment by antonkomarev** [comment]
> thanks, just added to my profile!

Looks good!

**Comment by Trkzi-Omar** [comment]
> This is a great feature, thanks for adding it @Trkzi-Omar!
> 
> @antonkomarev can you ping here once you deploy this please? I would like to add it to my profile.

I am glad you found it interesting. Happy to contribute to OSS 🙌

**Pull request merged**
